const PERSON_LOG_TYPES = Object.freeze({
  LOGIN: 1,
  SESSION_REFRESH: 8,
  PAGE_VISIT: 7,
  IMPERSONATION_START: 30,
  IMPERSONATION_END: 31,
  IMPERSONATION_EXTEND: 32,
});

module.exports = { PERSON_LOG_TYPES };
